server:
  port: 8080
spring:
  application:
    name: basicinfo
  datasource:
    url: jdbc:h2:mem:h2db
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console